creditCalculator/bank/urls.py
from django.urls import path

from bank.views.bank_view import create_bank, get_banks, edit_bank, delete_bank, get_all_banks_clients
from bank.views.client_view import create_client, get_clients, edit_client, delete_client
from bank.views.credit_offer_view import get_credit_offers, create_credit_offer, edit_credit_offer, delete_credit_offer
from bank.views.credit_view import get_credits, create_credit, edit_credit, delete_credit
from bank.views.payment_view import get_payment_for_credit, get_payment_for_credit_offer

app_name = 'bank'

urlpatterns = [

    path('create_bank/', create_bank, name='create_bank'),
    path('get_banks/', get_banks, name='get_banks'),
    path("edit_bank/<int:bank_id>/", edit_bank, name='edit_bank'),
    path("delete_bank/<int:bank_id>/", delete_bank, name='delete_bank'),
    path("get_all_banks_clients/<int:bank_id>/", get_all_banks_clients, name='get_all_banks_clients'),

    path('create_client/', create_client, name='create_client'),
    path('get_clients/', get_clients, name='get_clients'),
    path("edit_client/<int:client_id>/", edit_client, name='edit_client'),
    path("delete_client/<int:client_id>/", delete_client, name='delete_client'),

    path('get_credits/', get_credits, name='get_credits'),
    path('create_credit/', create_credit, name='create_credit'),
    path("edit_credit/<int:credit_id>/", edit_credit, name='edit_credit'),
    path("delete_credit/<int:credit_id>/", delete_credit, name='delete_credit'),

    path('get_credit_offer/', get_credit_offers, name='get_credit_offer'),
    path('create_credit_offer/', create_credit_offer, name='create_credit_offer'),
    path("edit_credit_offer/<int:credit_offer_id>/", edit_credit_offer, name='edit_credit_offer'),
    path("delete_credit_offer/<int:credit_offer_id>/", delete_credit_offer, name='delete_credit_offer'),

    path('get_payment_credit/<int:credit_id>/', get_payment_for_credit, name='get_payment_for_credit'),
    path('get_payment_credit_offer/<int:credit_offer_id>/', get_payment_for_credit_offer,
         name='get_payment_for_credit_offer'),

]

creditCalculator/creditCalculator/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from bank.views.view import home
from bank.views.api_view import ClientViewSet, BankViewSet, CreditOfferViewSet, CreditViewSet, \
    PaymentViewSet

router = DefaultRouter()
router.register(r'api/v1/clients', ClientViewSet)
router.register(r'api/v1/banks', BankViewSet)
router.register(r'api/v1/credit_offers', CreditOfferViewSet)
router.register(r'api/v1/credits', CreditViewSet)
router.register(r'api/v1/payments', PaymentViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('users/', include('users.urls', namespace='users')),
    path('', include('bank.urls', namespace='bank')),

]

urlpatterns += router.urls

creditCalculator/users/urls.py
from django.urls import path

from users.views import registration, login, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('logout/', logout, name='logout'),
]

creditCalculator/users/models.py
from django.db import models

# Create your models here.

creditCalculator/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

creditCalculator/users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages, auth
from django.urls import reverse
from users.forms import UserLoginForm, UserRegistrationForm


def registration(request):
    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Поздравляю {request.POST.get("username")}! Вы успешно зарегистрировались!')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    return render(request, 'users/registration.html', {'form': form})


def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                messages.success(request, f'{request.POST.get("username")}, Вы успешно авторизовались!')
                return HttpResponseRedirect(reverse('home'))
    else:
        form = UserLoginForm()

    return render(request, 'users/login.html', {'form': form})


def logout(request):
    auth.logout(request)
    messages.warning(request, 'Вы вышли из аккаунта!')
    return HttpResponseRedirect(reverse('home'))

creditCalculator/users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-4">
        <form method="POST" novalidate>
            {% csrf_token %}
            <legend class="border-bottom mb-4 text-center">Вход</legend>
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Войти</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Нужен аккаунт? <a class="ml-2" href="{% url 'users:registration' %}">Регистрация</a>
            </small>
        </div>
       </div>
    </div>
</div>
{% endblock content %}

creditCalculator/users/templates/users/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container center">
    <div class="row justify-content-center">
        <div class="col-xs">
        <form method="POST" novalidate>
            {% csrf_token %}
            <fieldset class="form-group" >
                <legend class="border-bottom text-center">Регистрация</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Регистрация</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Уже есть аккаунт? <a class="ml-2" href="{% url 'users:login' %}">Вход</a>
            </small>
        </div>
    </div>
  </div>
</div>
{% endblock %}